import json
import os

def create_notebook(folder_name, file_name, cells):
    os.makedirs(os.path.join("d:/Deep_Learning_Tasks", folder_name), exist_ok=True)
    filepath = os.path.join("d:/Deep_Learning_Tasks", folder_name, file_name)
    
    notebook_content = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": cells
    }
    
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(notebook_content, f, indent=1)
    print(f"Created: {filepath}")

def build_task_1():
    cells = []
    
    # MD Cell
    cells.append({
        "cell_type": "markdown",
        "id": "t1-md1",
        "metadata": {},
        "source": [
            "# Task 1: Vectorized Multi-Layer Perceptron (MLP) Forward & Backward Pass from Scratch\n",
            "\n",
            "**Objective:** Master the mathematical foundations of gradient descent by deriving and implementing multi-layer backpropagation equations using raw matrix calculus from first principles.\n",
            "\n",
            "### Mathematical Formulation\n",
            "\n",
            "#### Forward Pass\n",
            "For a layer $l$ with weight matrix $W^{[l]}$ and bias vector $b^{[l]}$:\n",
            "$$Z^{[l]} = A^{[l-1]} W^{[l]} + b^{[l]}$$\n",
            "$$A^{[l]} = g^{[l]}(Z^{[l]})$$\n",
            "\n",
            "#### Backward Pass (Vectorized)\n",
            "Let the loss be $L$. We compute gradients backward from the output layer $L$ to the input layer $1$:\n",
            "1. Output gradient w.r.t logits (for Softmax + Cross Entropy):\n",
            "   $$dZ^{[L]} = A^{[L]} - Y$$\n",
            "2. Gradient w.r.t weights and biases of layer $l$:\n",
            "   $$dW^{[l]} = \\frac{1}{m} A^{[l-1]\\top} dZ^{[l]}$$\n",
            "   $$db^{[l]} = \\frac{1}{m} \\sum_{i=1}^{m} dZ^{[l]}_i$$\n",
            "3. Gradient w.r.t activation of preceding layer:\n",
            "   $$dA^{[l-1]} = dZ^{[l]} W^{[l]\\top}$$\n",
            "4. Gradient w.r.t logits of preceding layer:\n",
            "   $$dZ^{[l-1]} = dA^{[l-1]} \\odot g^{[l-1]\\prime}(Z^{[l-1]})$$\n",
            "   where $\\odot$ represents the Hadamard (element-wise) product and $g^\\prime$ is the activation derivative."
        ]
    })
    
    # Code Cell (Implementation)
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t1-code1",
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "# Activation Functions and their Derivatives\n",
            "def relu(x):\n",
            "    # ReLU activation function\n",
            "    return np.maximum(0, x)\n",
            "\n",
            "def relu_derivative(x):\n",
            "    # Derivative of ReLU activation function\n",
            "    return (x > 0).astype(float)\n",
            "\n",
            "def sigmoid(x):\n",
            "    # Sigmoid activation function\n",
            "    return 1 / (1 + np.exp(-np.clip(x, -500, 500)))\n",
            "\n",
            "def sigmoid_derivative(x):\n",
            "    # Derivative of Sigmoid activation function\n",
            "    s = sigmoid(x)\n",
            "    return s * (1 - s)\n",
            "\n",
            "def stable_softmax(x):\n",
            "    # Softmax activation function with subtraction of max for numerical stability\n",
            "    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))\n",
            "    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)\n",
            "\n",
            "class DenseLayer:\n",
            "    def __init__(self, input_dim, output_dim, activation='relu'):\n",
            "        # Initialize weights using Xavier/Glorot normal distribution\n",
            "        self.W = np.random.randn(input_dim, output_dim) * np.sqrt(2.0 / (input_dim + output_dim))\n",
            "        self.b = np.zeros((1, output_dim))\n",
            "        \n",
            "        self.activation = activation\n",
            "        self.X_cache = None\n",
            "        self.Z_cache = None\n",
            "        \n",
            "        # Gradient accumulators\n",
            "        self.dW = None\n",
            "        self.db = None\n",
            "        \n",
            "    def forward(self, X):\n",
            "        # Forward pass: store caches for backpropagation\n",
            "        self.X_cache = X\n",
            "        self.Z_cache = np.dot(X, self.W) + self.b\n",
            "        \n",
            "        if self.activation == 'relu':\n",
            "            return relu(self.Z_cache)\n",
            "        elif self.activation == 'sigmoid':\n",
            "            return sigmoid(self.Z_cache)\n",
            "        elif self.activation == 'softmax':\n",
            "            return stable_softmax(self.Z_cache)\n",
            "        else:\n",
            "            return self.Z_cache\n",
            "            \n",
            "    def backward(self, dA):\n",
            "        # Backward pass: compute local derivatives and gradients w.r.t parameters\n",
            "        m = self.X_cache.shape[0]\n",
            "        \n",
            "        # Compute dZ = dLoss/dZ\n",
            "        if self.activation == 'relu':\n",
            "            dZ = dA * relu_derivative(self.Z_cache)\n",
            "        elif self.activation == 'sigmoid':\n",
            "            dZ = dA * sigmoid_derivative(self.Z_cache)\n",
            "        elif self.activation == 'softmax':\n",
            "            # softmax is handled in junction with cross-entropy in the loss layer\n",
            "            dZ = dA\n",
            "        else:\n",
            "            dZ = dA\n",
            "            \n",
            "        # Compute gradients w.r.t parameters\n",
            "        self.dW = np.dot(self.X_cache.T, dZ) / m\n",
            "        self.db = np.sum(dZ, axis=0, keepdims=True) / m\n",
            "        \n",
            "        # Return dA_prev to propagate back to previous layers\n",
            "        dA_prev = np.dot(dZ, self.W.T)\n",
            "        return dA_prev\n",
            "\n",
            "class MLPClassifier:\n",
            "    def __init__(self, layer_sizes, activations):\n",
            "        self.layers = []\n",
            "        for i in range(len(layer_sizes) - 1):\n",
            "            self.layers.append(DenseLayer(layer_sizes[i], layer_sizes[i+1], activations[i]))\n",
            "            \n",
            "    def forward(self, X):\n",
            "        out = X\n",
            "        for layer in self.layers:\n",
            "            out = layer.forward(out)\n",
            "        return out\n",
            "        \n",
            "    def backward(self, Y_pred, Y_true):\n",
            "        m = Y_true.shape[0]\n",
            "        # The gradient of cross entropy loss w.r.t logits of a final softmax layer is (Y_pred - Y_true)\n",
            "        dA = Y_pred - Y_true\n",
            "        \n",
            "        # Backpropagate through layers in reverse order\n",
            "        for layer in reversed(self.layers):\n",
            "            dA = layer.backward(dA)\n",
            "            \n",
            "    def update_weights(self, lr):\n",
            "        # Standard Gradient Descent Weight Updates\n",
            "        for layer in self.layers:\n",
            "            layer.W -= lr * layer.dW\n",
            "            layer.b -= lr * layer.db"
        ]
    })
    
    # Code Cell (Dataset & Training & Evaluation)
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t1-code2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Synthetic data generator: Spiral Dataset\n",
            "def generate_spiral_data(points_per_class=100, classes=3):\n",
            "    N = points_per_class\n",
            "    D = 2\n",
            "    K = classes\n",
            "    X = np.zeros((N * K, D))\n",
            "    y = np.zeros(N * K, dtype='uint8')\n",
            "    for j in range(K):\n",
            "        ix = range(N * j, N * (j + 1))\n",
            "        r = np.linspace(0.0, 1, N) # radius\n",
            "        t = np.linspace(j * 4, (j + 1) * 4, N) + np.random.randn(N) * 0.2 # theta\n",
            "        X[ix] = np.c_[r * np.sin(t), r * np.cos(t)]\n",
            "        y[ix] = j\n",
            "    \n",
            "    # Convert to one-hot encoding\n",
            "    Y_onehot = np.zeros((N * K, K))\n",
            "    Y_onehot[np.arange(N * K), y] = 1\n",
            "    return X, y, Y_onehot\n",
            "\n",
            "X, y, Y = generate_spiral_data(points_per_class=150, classes=3)\n",
            "\n",
            "# Initialize 3-layer MLP\n",
            "# 2 inputs -> 64 hidden units (ReLU) -> 32 hidden units (ReLU) -> 3 outputs (Softmax)\n",
            "mlp = MLPClassifier([2, 64, 32, 3], ['relu', 'relu', 'softmax'])\n",
            "\n",
            "# Train network\n",
            "epochs = 2000\n",
            "lr = 0.5\n",
            "loss_history = []\n",
            "\n",
            "for epoch in range(epochs):\n",
            "    # Forward pass\n",
            "    probs = mlp.forward(X)\n",
            "    \n",
            "    # Calculate categorical cross-entropy loss\n",
            "    loss = -np.mean(np.sum(Y * np.log(probs + 1e-15), axis=-1))\n",
            "    loss_history.append(loss)\n",
            "    \n",
            "    # Backward pass\n",
            "    mlp.backward(probs, Y)\n",
            "    \n",
            "    # Weights adjustments\n",
            "    mlp.update_weights(lr)\n",
            "    \n",
            "    if epoch % 200 == 0:\n",
            "        accuracy = np.mean(np.argmax(probs, axis=-1) == y)\n",
            "        print(f\"Epoch {epoch:4d} | Cross Entropy Loss: {loss:.4f} | Accuracy: {accuracy*100:.2f}%\")\n",
            "\n",
            "# Plotting results\n",
            "plt.figure(figsize=(12, 5))\n",
            "plt.subplot(1, 2, 1)\n",
            "plt.plot(loss_history, 'r-', lw=2)\n",
            "plt.title('Loss Convergence Curve')\n",
            "plt.xlabel('Epoch')\n",
            "plt.ylabel('Cross-Entropy Loss')\n",
            "plt.grid(True)\n",
            "\n",
            "plt.subplot(1, 2, 2)\n",
            "# Plot decision boundary\n",
            "h = 0.02\n",
            "x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1\n",
            "y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1\n",
            "xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))\n",
            "grid_points = np.c_[xx.ravel(), yy.ravel()]\n",
            "grid_preds = np.argmax(mlp.forward(grid_points), axis=-1)\n",
            "grid_preds = grid_preds.reshape(xx.shape)\n",
            "plt.contourf(xx, yy, grid_preds, cmap=plt.cm.Spectral, alpha=0.8)\n",
            "plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.Spectral, edgecolors='k')\n",
            "plt.title('MLP Learned Decision Boundaries')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    })
    
    create_notebook("Task01_Vectorized_MLP", "Vectorized_MLP.ipynb", cells)

def build_task_2():
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "id": "t2-md1",
        "metadata": {},
        "source": [
            "# Task 2: Empirical Diagnostic of Custom Weight Initializations and Gradient Vanishing\n",
            "\n",
            "**Objective:** Analyze mathematical training instability in deep neural networks by tracking activation distributions and gradient magnitudes under varying initialization distributions.\n",
            "\n",
            "### Weight Initializations\n",
            "1. **Random Normal Initialization:**\n",
            "   $$W \\sim \\mathcal{N}(0, \\sigma^2)$$\n",
            "2. **Xavier (Glorot) Normal Initialization:**\n",
            "   $$W \\sim \\mathcal{N}\\left(0, \\frac{2}{n_{in} + n_{out}}\\right)$$\n",
            "3. **Kaiming (He) Normal Initialization:**\n",
            "   $$W \\sim \\mathcal{N}\\left(0, \\frac{2}{n_{in}}\\right)$$"
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t2-code1",
        "metadata": {},
        "outputs": [],
        "source": [
            "import torch\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "# Disable gradient computation globally to ensure manual tracking\n",
            "torch.set_grad_enabled(False)\n",
            "\n",
            "# Custom initialization routines\n",
            "def random_normal_init(shape, std=1.0):\n",
            "    return torch.randn(shape) * std\n",
            "\n",
            "def xavier_normal_init(shape):\n",
            "    n_in, n_out = shape[0], shape[1]\n",
            "    std = np.sqrt(2.0 / (n_in + n_out))\n",
            "    return torch.randn(shape) * std\n",
            "\n",
            "def kaiming_normal_init(shape):\n",
            "    n_in = shape[0]\n",
            "    std = np.sqrt(2.0 / n_in)\n",
            "    return torch.randn(shape) * std\n",
            "\n",
            "class CustomLinearModule:\n",
            "    def __init__(self, input_dim, output_dim, init_fn):\n",
            "        self.W = init_fn((input_dim, output_dim))\n",
            "        self.b = torch.zeros(output_dim)\n",
            "        self.X_cache = None\n",
            "        self.Z_cache = None\n",
            "        self.dW = None\n",
            "        \n",
            "    def forward(self, X):\n",
            "        self.X_cache = X\n",
            "        self.Z_cache = torch.matmul(X, self.W) + self.b\n",
            "        return torch.relu(self.Z_cache)\n",
            "        \n",
            "    def backward(self, dAct):\n",
            "        # Local gradient: relu derivative\n",
            "        dZ = dAct * (self.Z_cache > 0).float()\n",
            "        # Parameters gradient estimation\n",
            "        self.dW = torch.matmul(self.X_cache.t(), dZ) / X_cache.shape[0]\n",
            "        # Return gradient to pass backward\n",
            "        dAct_prev = torch.matmul(dZ, self.W.t())\n",
            "        return dAct_prev"
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t2-code2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Setup a 20-Layer deep network with custom tracking\n",
            "layer_dim = 128\n",
            "num_layers = 20\n",
            "batch_size = 64\n",
            "X_input = torch.randn(batch_size, layer_dim)\n",
            "\n",
            "initializations = {\n",
            "    \"Large Random Normal (std=1.0)\": lambda shape: random_normal_init(shape, std=1.0),\n",
            "    \"Small Random Normal (std=0.01)\": lambda shape: random_normal_init(shape, std=0.01),\n",
            "    \"Xavier Normal\": xavier_normal_init,\n",
            "    \"Kaiming Normal\": kaiming_normal_init\n",
            "}\n",
            "\n",
            "results = {}\n",
            "\n",
            "for init_name, init_fn in initializations.items():\n",
            "    # Instantiate layers\n",
            "    layers = [CustomLinearModule(layer_dim, layer_dim, init_fn) for _ in range(num_layers)]\n",
            "    \n",
            "    # Forward pass tracking activation statistics\n",
            "    activations = [X_input]\n",
            "    current_act = X_input\n",
            "    for layer in layers:\n",
            "        current_act = layer.forward(current_act)\n",
            "        activations.append(current_act)\n",
            "        \n",
            "    # Setup mock output gradient for manual backward\n",
            "    dAct = torch.randn(batch_size, layer_dim)\n",
            "    grad_magnitudes = []\n",
            "    \n",
            "    # Backward pass tracking gradient magnitudes\n",
            "    for layer in reversed(layers):\n",
            "        dAct = layer.backward(dAct)\n",
            "        grad_magnitudes.append(torch.mean(torch.abs(dAct)).item())\n",
            "        \n",
            "    # Store statistics\n",
            "    results[init_name] = {\n",
            "        \"activation_means\": [torch.mean(act).item() for act in activations],\n",
            "        \"activation_vars\": [torch.var(act).item() for act in activations],\n",
            "        \"grad_mags\": list(reversed(grad_magnitudes))\n",
            "    }\n",
            "\n",
            "# Plotting Statistics\n",
            "plt.figure(figsize=(15, 10))\n",
            "\n",
            "# Activation Variance vs Layer\n",
            "plt.subplot(2, 2, 1)\n",
            "for init_name, stats in results.items():\n",
            "    plt.plot(stats[\"activation_vars\"], label=init_name, lw=2)\n",
            "plt.title(\"Activation Variance across Layers\")\n",
            "plt.xlabel(\"Layer Index\")\n",
            "plt.ylabel(\"Variance\")\n",
            "plt.grid(True)\n",
            "plt.legend()\n",
            "\n",
            "# Activation Means vs Layer\n",
            "plt.subplot(2, 2, 2)\n",
            "for init_name, stats in results.items():\n",
            "    plt.plot(stats[\"activation_means\"], label=init_name, lw=2)\n",
            "plt.title(\"Activation Means across Layers\")\n",
            "plt.xlabel(\"Layer Index\")\n",
            "plt.ylabel(\"Mean\")\n",
            "plt.grid(True)\n",
            "plt.legend()\n",
            "\n",
            "# Gradient Magnitudes vs Layer\n",
            "plt.subplot(2, 2, 3)\n",
            "for init_name, stats in results.items():\n",
            "    plt.plot(stats[\"grad_mags\"], label=init_name, lw=2)\n",
            "plt.title(\"Gradient Magnitudes across Layers (Backwards)\")\n",
            "plt.xlabel(\"Layer Index\")\n",
            "plt.ylabel(\"Mean Absolute Gradient\")\n",
            "plt.yscale('log')\n",
            "plt.grid(True)\n",
            "plt.legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    })
    
    create_notebook("Task02_Weight_Init", "Weight_Initialization_Diagnostic.ipynb", cells)

def build_task_3():
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "id": "t3-md1",
        "metadata": {},
        "source": [
            "# Task 3: Vectorized Convolutional Forward Pass via im2col Transformation from Scratch\n",
            "\n",
            "**Objective:** Build high-performance convolutions by transforming sliding spatial windows into a single optimized matrix multiplication ($Y = W_{flat} \\cdot X_{im2col} + b$).\n",
            "\n",
            "### Mechanics\n",
            "\n",
            "The standard 2D convolution requires 6 nested loops (batch, channels, height, width, kernel_h, kernel_w). By flattening all image patches into columns of a large matrix, we compute spatial filters efficiently using matrix operations."
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t3-code1",
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "\n",
            "def get_im2col_indices(x_shape, kh, kw, padding=1, stride=1):\n",
            "    # Extract dimensions\n",
            "    N, C, H, W = x_shape\n",
            "    # Compute output sizes\n",
            "    out_h = int((H + 2 * padding - kh) / stride + 1)\n",
            "    out_w = int((W + 2 * padding - kw) / stride + 1)\n",
            "    \n",
            "    # Generate indices matrices\n",
            "    i0 = np.repeat(np.arange(kh), kw)\n",
            "    i0 = np.tile(i0, C)\n",
            "    i1 = stride * np.repeat(np.arange(out_h), out_w)\n",
            "    j0 = np.tile(np.arange(kw), kh * C)\n",
            "    j1 = stride * np.tile(np.arange(out_w), out_h)\n",
            "    \n",
            "    i = i0.reshape(-1, 1) + i1.reshape(1, -1)\n",
            "    j = j0.reshape(-1, 1) + j1.reshape(1, -1)\n",
            "    k = np.repeat(np.arange(C), kh * kw).reshape(-1, 1)\n",
            "    return (k.astype(int), i.astype(int), j.astype(int))\n",
            "\n",
            "def im2col_indices(x, kh, kw, padding=1, stride=1):\n",
            "    # Zero-pad the input image\n",
            "    x_padded = np.pad(x, ((0, 0), (0, 0), (padding, padding), (padding, padding)), mode='constant')\n",
            "    k, i, j = get_im2col_indices(x.shape, kh, kw, padding, stride)\n",
            "    \n",
            "    cols = x_padded[:, k, i, j]\n",
            "    C = x.shape[1]\n",
            "    cols = cols.transpose(1, 2, 0).reshape(kh * kw * C, -1)\n",
            "    return cols\n",
            "\n",
            "class Conv2DScratch:\n",
            "    def __init__(self, in_channels, out_channels, kernel_size, padding=1, stride=1):\n",
            "        self.in_channels = in_channels\n",
            "        self.out_channels = out_channels\n",
            "        self.kh = self.kw = kernel_size\n",
            "        self.padding = padding\n",
            "        self.stride = stride\n",
            "        \n",
            "        # Initialize parameters\n",
            "        self.W = np.random.randn(out_channels, in_channels, self.kh, self.kw) * np.sqrt(2.0 / (in_channels * self.kh * self.kw))\n",
            "        self.b = np.zeros((out_channels, 1))\n",
            "        \n",
            "    def forward(self, X):\n",
            "        N, C, H, W = X.shape\n",
            "        out_h = int((H + 2 * self.padding - self.kh) / self.stride + 1)\n",
            "        out_w = int((W + 2 * self.padding - self.kw) / self.stride + 1)\n",
            "        \n",
            "        # Transform input array into columns\n",
            "        X_col = im2col_indices(X, self.kh, self.kw, self.padding, self.stride)\n",
            "        # Flatten filter weights\n",
            "        W_row = self.W.reshape(self.out_channels, -1)\n",
            "        \n",
            "        # Single dot product execution\n",
            "        out = np.dot(W_row, X_col) + self.b\n",
            "        \n",
            "        # Reshape to (out_channels, out_h, out_w, N) -> Transpose to (N, out_channels, out_h, out_w)\n",
            "        out = out.reshape(self.out_channels, out_h, out_w, N)\n",
            "        out = out.transpose(3, 0, 1, 2)\n",
            "        return out"
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t3-code2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Numerical verification against PyTorch\n",
            "N, C, H, W = 4, 3, 32, 32\n",
            "in_c, out_c = 3, 8\n",
            "k_size = 3\n",
            "padding = 1\n",
            "stride = 2\n",
            "\n",
            "# Generate sample image\n",
            "x_np = np.random.randn(N, C, H, W).astype(np.float32)\n",
            "x_tensor = torch.tensor(x_np)\n",
            "\n",
            "# Instanciate Custom Conv\n",
            "custom_conv = Conv2DScratch(in_channels=in_c, out_channels=out_c, kernel_size=k_size, padding=padding, stride=stride)\n",
            "\n",
            "# Instantiate PyTorch equivalent Conv\n",
            "pt_conv = nn.Conv2d(in_channels=in_c, out_channels=out_c, kernel_size=k_size, padding=padding, stride=stride)\n",
            "pt_conv.weight.data = torch.tensor(custom_conv.W, dtype=torch.float32)\n",
            "pt_conv.bias.data = torch.tensor(custom_conv.b.squeeze(), dtype=torch.float32)\n",
            "\n",
            "# Compare outputs\n",
            "custom_out = custom_conv.forward(x_np)\n",
            "pt_out = pt_conv(x_tensor).detach().numpy()\n",
            "\n",
            "difference = np.abs(custom_out - pt_out)\n",
            "max_diff = np.max(difference)\n",
            "mean_diff = np.mean(difference)\n",
            "\n",
            "print(f\"Maximum Absolute Discrepancy: {max_diff:.8e}\")\n",
            "print(f\"Mean Absolute Discrepancy: {mean_diff:.8e}\")\n",
            "assert max_diff < 1e-5, \"Failed: Outputs deviate significantly!\"\n",
            "print(\"Success: Custom im2col forward pass mathematically matches PyTorch Conv2D!\")"
        ]
    })
    
    create_notebook("Task03_Vectorized_Conv", "Vectorized_Convolution_im2col.ipynb", cells)

def build_task_4():
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "id": "t4-md1",
        "metadata": {},
        "source": [
            "# Task 4: Custom Gradient Descent Optimizers with Momentum, RMSprop, and Adam\n",
            "\n",
            "**Objective:** Master adaptive learning rate mechanics and temporal update optimization algorithms by implementing high-performance weight updates from scratch using raw PyTorch tensor math (no `torch.optim`)."
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t4-code1",
        "metadata": {},
        "outputs": [],
        "source": [
            "import torch\n",
            "import torch.nn as nn\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.datasets import make_moons\n",
            "\n",
            "class CustomOptimizer:\n",
            "    def __init__(self, params):\n",
            "        self.params = list(params)\n",
            "        \n",
            "    def zero_grad(self):\n",
            "        for p in self.params:\n",
            "            if p.grad is not None:\n",
            "                p.grad.zero_()\n",
            "\n",
            "class CustomSGDMomentum(CustomOptimizer):\n",
            "    def __init__(self, params, lr=0.01, beta=0.9):\n",
            "        super().__init__(params)\n",
            "        self.lr = lr\n",
            "        self.beta = beta\n",
            "        self.velocities = [torch.zeros_like(p) for p in self.params]\n",
            "        \n",
            "    def step(self):\n",
            "        for p, v in zip(self.params, self.velocities):\n",
            "            if p.grad is None: continue\n",
            "            # Update velocity\n",
            "            v.mul_(self.beta).add_(p.grad, alpha=1 - self.beta)\n",
            "            # Update parameter\n",
            "            p.add_(v, alpha=-self.lr)\n",
            "\n",
            "class CustomRMSprop(CustomOptimizer):\n",
            "    def __init__(self, params, lr=0.001, alpha=0.99, eps=1e-8):\n",
            "        super().__init__(params)\n",
            "        self.lr = lr\n",
            "        self.alpha = alpha\n",
            "        self.eps = eps\n",
            "        self.squared_grads = [torch.zeros_like(p) for p in self.params]\n",
            "        \n",
            "    def step(self):\n",
            "        for p, s in zip(self.params, self.squared_grads):\n",
            "            if p.grad is None: continue\n",
            "            # Moving average of squared gradients\n",
            "            s.mul_(self.alpha).addcmul_(p.grad, p.grad, value=1 - self.alpha)\n",
            "            # Param updates\n",
            "            denom = s.sqrt().add_(self.eps)\n",
            "            p.addcdiv_(p.grad, denom, value=-self.lr)\n",
            "\n",
            "class CustomAdam(CustomOptimizer):\n",
            "    def __init__(self, params, lr=0.001, betas=(0.9, 0.999), eps=1e-8):\n",
            "        super().__init__(params)\n",
            "        self.lr = lr\n",
            "        self.beta1, self.beta2 = betas\n",
            "        self.eps = eps\n",
            "        self.m = [torch.zeros_like(p) for p in self.params]\n",
            "        self.v = [torch.zeros_like(p) for p in self.params]\n",
            "        self.t = 0\n",
            "        \n",
            "    def step(self):\n",
            "        self.t += 1\n",
            "        for p, m_prev, v_prev in zip(self.params, self.m, self.v):\n",
            "            if p.grad is None: continue\n",
            "            \n",
            "            # First moment update\n",
            "            m_prev.mul_(self.beta1).add_(p.grad, alpha=1 - self.beta1)\n",
            "            \n",
            "            # Second moment update\n",
            "            v_prev.mul_(self.beta2).addcmul_(p.grad, p.grad, value=1 - self.beta2)\n",
            "            \n",
            "            # Bias corrections\n",
            "            bias_corr1 = 1 - self.beta1 ** self.t\n",
            "            bias_corr2 = 1 - self.beta2 ** self.t\n",
            "            \n",
            "            step_size = self.lr / bias_corr1\n",
            "            denom = (v_prev.sqrt() / np.sqrt(bias_corr2)).add_(self.eps)\n",
            "            \n",
            "            # Update step\n",
            "            p.addcdiv_(m_prev, denom, value=-step_size)"
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t4-code2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Create synthetic double-moon dataset\n",
            "X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)\n",
            "X = torch.tensor(X, dtype=torch.float32)\n",
            "y = torch.tensor(y, dtype=torch.long)\n",
            "\n",
            "def build_model():\n",
            "    # Simple MLP classifier\n",
            "    return nn.Sequential(\n",
            "        nn.Linear(2, 32),\n",
            "        nn.ReLU(),\n",
            "        nn.Linear(32, 16),\n",
            "        nn.ReLU(),\n",
            "        nn.Linear(16, 2)\n",
            "    )\n",
            "\n",
            "epochs = 200\n",
            "criterion = nn.CrossEntropyLoss()\n",
            "\n",
            "optimizers_to_test = [\n",
            "    (\"SGD with Momentum\", lambda p: CustomSGDMomentum(p, lr=0.1, beta=0.9)),\n",
            "    (\"RMSprop\", lambda p: CustomRMSprop(p, lr=0.01, alpha=0.99)),\n",
            "    (\"Adam\", lambda p: CustomAdam(p, lr=0.01, betas=(0.9, 0.999)))\n",
            "]\n",
            "\n",
            "losses_history = {}\n",
            "\n",
            "for name, opt_builder in optimizers_to_test:\n",
            "    model = build_model()\n",
            "    optimizer = opt_builder(model.parameters())\n",
            "    losses_history[name] = []\n",
            "    \n",
            "    for epoch in range(epochs):\n",
            "        optimizer.zero_grad()\n",
            "        preds = model(X)\n",
            "        loss = criterion(preds, y)\n",
            "        loss.backward()\n",
            "        optimizer.step()\n",
            "        \n",
            "        losses_history[name].append(loss.item())\n",
            "        \n",
            "        if (epoch + 1) % 50 == 0:\n",
            "            print(f\"{name:18s} | Epoch {epoch+1:3d}/{epochs} | Loss: {loss.item():.4f}\")\n",
            "\n",
            "# Visualizing convergence\n",
            "plt.figure(figsize=(10, 6))\n",
            "for name, losses in losses_history.items():\n",
            "    plt.plot(losses, label=name, lw=2.5)\n",
            "plt.title('Loss Convergence Profiles across Optimizers')\n",
            "plt.xlabel('Epoch')\n",
            "plt.ylabel('Cross-Entropy Loss')\n",
            "plt.grid(True)\n",
            "plt.legend()\n",
            "plt.show()"
        ]
    })
    
    create_notebook("Task04_Custom_Optimizers", "Custom_Optimizers.ipynb", cells)

def build_task_5():
    cells = []
    
    cells.append({
        "cell_type": "markdown",
        "id": "t5-md1",
        "metadata": {},
        "source": [
            "# Task 5: Custom Batch Normalization and Layer Normalization Forward/Backward Propagation\n",
            "\n",
            "**Objective:** Stablize internal covariate shifts by building structural normalization layers with manual gradient derivations, bypassing PyTorch Autograd."
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t5-code1",
        "metadata": {},
        "outputs": [],
        "source": [
            "import torch\n",
            "import numpy as np\n",
            "\n",
            "class CustomBatchNormFunction:\n",
            "    @staticmethod\n",
            "    def forward(x, gamma, beta, running_mean, running_var, eps=1e-5, training=True, momentum=0.1):\n",
            "        # x shape: (N, D)\n",
            "        if training:\n",
            "            mean = x.mean(dim=0)\n",
            "            var = x.var(dim=0, unbiased=False)\n",
            "            \n",
            "            # Normalize\n",
            "            x_hat = (x - mean) / torch.sqrt(var + eps)\n",
            "            \n",
            "            # Update running stats\n",
            "            running_mean.copy_((1 - momentum) * running_mean + momentum * mean)\n",
            "            running_var.copy_((1 - momentum) * running_var + momentum * var * x.shape[0] / (x.shape[0] - 1))\n",
            "            \n",
            "            # Cache variables for backprop\n",
            "            cache = (x, x_hat, mean, var, gamma, eps)\n",
            "        else:\n",
            "            x_hat = (x - running_mean) / torch.sqrt(running_var + eps)\n",
            "            cache = None\n",
            "            \n",
            "        y = gamma * x_hat + beta\n",
            "        return y, cache\n",
            "        \n",
            "    @staticmethod\n",
            "    def backward(dy, cache):\n",
            "        # dy shape: (N, D)\n",
            "        x, x_hat, mean, var, gamma, eps = cache\n",
            "        N, D = dy.shape\n",
            "        \n",
            "        # Gradients w.r.t parameters\n",
            "        dgamma = torch.sum(dy * x_hat, dim=0)\n",
            "        dbeta = torch.sum(dy, dim=0)\n",
            "        \n",
            "        # Intermediate gradients w.r.t normalization formula\n",
            "        dx_hat = dy * gamma\n",
            "        dvar = torch.sum(dx_hat * (x - mean) * -0.5 * (var + eps)**(-1.5), dim=0)\n",
            "        dmean = torch.sum(dx_hat * -1.0 / torch.sqrt(var + eps), dim=0) + dvar * torch.mean(-2.0 * (x - mean), dim=0)\n",
            "        \n",
            "        # Final inputs gradient\n",
            "        dx = dx_hat / torch.sqrt(var + eps) + dvar * 2.0 * (x - mean) / N + dmean / N\n",
            "        return dx, dgamma, dbeta\n",
            "\n",
            "class CustomLayerNormFunction:\n",
            "    @staticmethod\n",
            "    def forward(x, gamma, beta, eps=1e-5):\n",
            "        # x shape: (N, D) - normalization is done per sample across features D\n",
            "        mean = x.mean(dim=-1, keepdim=True)\n",
            "        var = x.var(dim=-1, keepdim=True, unbiased=False)\n",
            "        \n",
            "        x_hat = (x - mean) / torch.sqrt(var + eps)\n",
            "        y = gamma * x_hat + beta\n",
            "        \n",
            "        cache = (x, x_hat, mean, var, gamma, eps)\n",
            "        return y, cache\n",
            "        \n",
            "    @staticmethod\n",
            "    def backward(dy, cache):\n",
            "        x, x_hat, mean, var, gamma, eps = cache\n",
            "        N, D = dy.shape\n",
            "        \n",
            "        # Gradients w.r.t parameters\n",
            "        dgamma = torch.sum(dy * x_hat, dim=0)\n",
            "        dbeta = torch.sum(dy, dim=0)\n",
            "        \n",
            "        # Inputs gradients via Layer Normalization derivatives\n",
            "        dx_hat = dy * gamma\n",
            "        dvar = torch.sum(dx_hat * (x - mean) * -0.5 * (var + eps)**(-1.5), dim=-1, keepdim=True)\n",
            "        dmean = torch.sum(dx_hat * -1.0 / torch.sqrt(var + eps), dim=-1, keepdim=True) + dvar * torch.mean(-2.0 * (x - mean), dim=-1, keepdim=True)\n",
            "        \n",
            "        dx = dx_hat / torch.sqrt(var + eps) + dvar * 2.0 * (x - mean) / D + dmean / D\n",
            "        return dx, dgamma, dbeta"
        ]
    })
    
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "id": "t5-code2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Verify custom implementation using PyTorch Autograd\n",
            "N, D = 16, 8\n",
            "x = torch.randn(N, D, requires_grad=True)\n",
            "gamma = torch.ones(D, requires_grad=True)\n",
            "beta = torch.zeros(D, requires_grad=True)\n",
            "\n",
            "# Test Batch Norm\n",
            "running_mean = torch.zeros(D)\n",
            "running_var = torch.ones(D)\n",
            "\n",
            "# PyTorch output\n",
            "pt_bn = torch.nn.BatchNorm1d(D, eps=1e-5, momentum=0.1)\n",
            "pt_bn.weight.data = gamma.data.clone()\n",
            "pt_bn.bias.data = beta.data.clone()\n",
            "pt_y = pt_bn(x)\n",
            "\n",
            "# Custom output\n",
            "custom_y, cache = CustomBatchNormFunction.forward(x, gamma, beta, running_mean, running_var, eps=1e-5, training=True)\n",
            "\n",
            "print(\"BatchNorm Forward Difference:\", torch.abs(pt_y - custom_y).max().item())\n",
            "\n",
            "# Backward Validation\n",
            "dy = torch.randn(N, D)\n",
            "pt_y.backward(dy)\n",
            "\n",
            "dx_custom, dgamma_custom, dbeta_custom = CustomBatchNormFunction.backward(dy, cache)\n",
            "\n",
            "print(\"BatchNorm Input Gradient Difference:\", torch.abs(x.grad - dx_custom).max().item())\n",
            "print(\"BatchNorm Gamma Gradient Difference:\", torch.abs(gamma.grad - dgamma_custom).max().item())\n",
            "print(\"BatchNorm Beta Gradient Difference:\", torch.abs(beta.grad - dbeta_custom).max().item())\n",
            "\n",
            "assert torch.abs(x.grad - dx_custom).max().item() < 1e-5, \"Failed Batch Norm Gradient Match!\"\n",
            "print(\"Success: Batch Normalization custom gradients match PyTorch Autograd!\")"
        ]
    })
    
    create_notebook("Task05_BatchNorm_LayerNorm", "Custom_Normalization.ipynb", cells)

if __name__ == "__main__":
    create_notebook("Task01_Vectorized_MLP", "Vectorized_MLP.ipynb", []) # Test directory setup
    build_task_1()
    build_task_2()
    build_task_3()
    build_task_4()
    build_task_5()
